detectron2_node:
  ros__parameters:
    detectron_config_file: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    pointcloud2_topic: "/realsense/camera/pointcloud"
    pcd_downsample_factor: 16
    categories: [0] # please check out COCO dataset category_id list if you want to config this